### Numpy

In [1]:
import numpy as np

**Creating arrays**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
# convert list to array
a = [1,2,3,4,5,7]
a = np.array(a)
a

array([1, 2, 3, 4, 5, 7])

In [ ]:
# Access the element from the array
print(a[2])
print(a[0])

3
1


In [11]:
# modify the values inside array
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  7])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**Multi-dementional array**

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# Access the element
print(n[0])
print(n[0,1])
print(n[2])
print(n[2,1:])

[1 2 3]
2
[7 8 9]
[8 9]


In [27]:
# Modify the array
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [32]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

**Randomly generated arrays**

In [ ]:
np.random.seed(2)
np.random.rand(5,2)  # uniform distribution

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.seed(2)
np.random.randn(5,2) # Normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [41]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

**Elememnt-wise operations**

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
print(a + 1)
print(a * 2)
print((10 + (a * 2)**2) / 100)

[1 2 3 4 5]
[0 2 4 6 8]
[0.1  0.14 0.26 0.46 0.74]


**Comparison operations**

In [48]:
a 

array([0, 1, 2, 3, 4])

In [50]:
a >= 2

array([False, False,  True,  True,  True])

In [51]:
a[a >= 2]

array([2, 3, 4])

**Summarizing operations**

In [55]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

0
4
2.0
1.4142135623730951
