### Linear Algebra 

In [109]:
import numpy as np

**Vector operations**

In [110]:
# columnn vector
u =np.array([2,4,5,6])  
v = np.array([1,0,0,2])

In [111]:
# scaler multiplication
2 * u

array([ 4,  8, 10, 12])

In [112]:
# addition
u + v

array([3, 4, 5, 8])

**Vector-Vector multiplication (Dot Product)**

In [113]:
u.shape , v.shape

((4,), (4,))

In [114]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = len(v)
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [115]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [116]:
# dot product using numpy
u.dot(v)

np.int64(14)

**Matrix-Vector multiplication**

In [117]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [118]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    
    n_rows = U.shape[0]
    result = np.zeros(n_rows)
    for i in range(n_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result

In [119]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [120]:
# multiplication using numpy 
U.dot(v)

array([14,  5,  5])

**Matrix-Matrix multiplication**

In [121]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [122]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [123]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [124]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**identity matrix(I)**

In [127]:
I = np.eye(3)

In [129]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [130]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

**Matrix inverse**

In [131]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [135]:
vs = V[[0,1,2]]
vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [137]:
vs_inv  = np.linalg.inv(vs)
vs_inv 

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [138]:
vs.dot(vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])